{% set name = "retype" %}
{% set version = "19.9.0" %}
{% set sha256 = "846fd135d3ee33c1bad387602a405d808cb99a9a7a47299bfd0e1d25dfb2fedd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - retype=retype:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - click
    - python
    - typed-ast

test:
  source_files:
    - tests
  imports:
    - retype
  commands:
    - retype --help
    - cd tests
    - python test_retype.py

about:
  home: https://github.com/ambv/retype
  license: MIT
  license_family: MIT
  # FIXME: The upstream PR might land some time >17.12.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Re-apply type annotations from .pyi stubs to your codebase.

  description: |
    When you run retype, it goes through all files you passed as SRC, finds the
    corresponding .pyi files in the types/ directory, and re-applies typing
    annotations from .pyi to the sources, using the Python 3 function and
    variable annotation syntax. The resulting combined sources are saved in
    typed-src/.

    You can also pass directories as sources, in which case retype will look
    for .py files in them recursively.

extra:
  recipe-maintainers:
    - bollwyvl
    - nehaljwani
