{% set version = "22.8.0" %}

package:
  name: retype
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/retype/retype-{{ version }}.tar.gz
  sha256: 4439b553c509741f3d08542decdde63365556dced1f4390eae0e22738d839fd9

build:
  number: 1
  noarch: python
  entry_points:
    - retype=retype.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=7
    - pathspec >=0.5.9,<1
    - python >={{ python_min }}
    - typed-ast >=1.3

test:
  requires:
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - retype
  commands:
    - retype --version
    - retype --help
    - cd tests
    - python test_retype.py

about:
  home: https://github.com/ambv/retype
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Re-apply type annotations from .pyi stubs to your codebase.

  description: |
    When you run retype, it goes through all files you passed as SRC, finds the
    corresponding .pyi files in the types/ directory, and re-applies typing
    annotations from .pyi to the sources, using the Python 3 function and
    variable annotation syntax. The resulting combined sources are saved in
    typed-src/.

    You can also pass directories as sources, in which case retype will look
    for .py files in them recursively.

extra:
  recipe-maintainers:
    - bollwyvl
    - nehaljwani
