appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MGBjhrJLfrkvEn4/8F3R/vFlHl3EFKkmxOnzGpUvzRufqOdmYJzbAIQACBoeZdnNfCu34pgptpS40q2228H9hSOudy9/KD6SA8FNFclK68bSwXORVRa2s1tPQovhpcyUrROv0HoKfTH+UjL42oTBpJW9rMRa6g2rsjOneQHQX9puwmBSnv+L2qE7ONPSInBp3kE4vNhnmqBG7Kytx+K0fI3S7K/WFKseCu0/qn5kWIe1FZgPgUPc8z5OONAo2ukTpB8I4XPjuXbHsvs+0eYhl7X08tChLighiOtAmostjfdcc3rztsvUe5XFwdZODUNCC6WP6KMVXSNyuAf3138Cfknzg79TiS7csDXFYtl1bskYuH8b9YmoxlUC3jEu1Q+QCxPYrqWaMZks1KBHrtimfAWq+eGBernZ0b5Ao+leu6FfK+9FZnXOTdXDBYD+LdJ+vn1IYOektIB/QuZt/5WC7ZgfQL+DshapcvuLxYRsOouZHt+Q4s2P1Ckk6Ak28P5JICp6ZJeL6clF1FNv3nbeTsuf44XSI4Vo7byakz8QbJjiYpzzygzOtriYT47L75O2s7xADaph9fhOiz2cpjb+A1kneUuLKvBAXX9Z4oiqfEwTTTdJIX7t/mSEE2URxpATq0V3snVEcGJWqFdOgegXuIZv/h/OYRXUwODO8qZ5bcw=}
conda_forge_output_validation: false
